<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <PackAsTool>true</PackAsTool>
    <ToolCommandName>tod</ToolCommandName>

    <PackageId>Tod</PackageId>
    <Version>0.6.1</Version>
    <Authors>dedale</Authors>
    <Description>Tod is a command line tool to run test on-demand on Jenkins.</Description>
    <PackageTags>tod;jenkins;test;automation</PackageTags>
    <RepositoryUrl>https://github.com/dedale/tod</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
    <PackageReference Include="LibGit2Sharp" Version="0.31.0" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="$(AssemblyName).Tests" />
    <InternalsVisibleTo Include="$(AssemblyName).Tests.Benchmarks" />
    <InternalsVisibleTo Include="$(AssemblyName).Windows" />
    <InternalsVisibleTo Include="$(AssemblyName).Windows.Tests" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>
  
  <Target Name="BuildWindowsAssembly" BeforeTargets="_IntermediatePack">
    <Error Text="Tod.Windows.csproj not found" Condition="!Exists('..\Tod.Windows\Tod.Windows.csproj')" />
    <MSBuild Projects="..\Tod.Windows\Tod.Windows.csproj"
             Targets="Restore;Build"
             Properties="Configuration=$(Configuration)" />

    <PropertyGroup>
      <TodWindowsOutputPath>$(ArtifactsPath)\bin\Tod.Windows\$(Configuration)_win-x64</TodWindowsOutputPath>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="$(TodWindowsOutputPath)\Tod.Windows.dll">
        <Pack>true</Pack>
        <PackagePath>tools/$(TargetFramework)/any/</PackagePath>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="$(TodWindowsOutputPath)\System.Data.SqlClient.dll">
        <Pack>true</Pack>
        <PackagePath>tools/$(TargetFramework)/any/</PackagePath>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="$(TodWindowsOutputPath)\System.DirectoryServices.AccountManagement.dll">
        <Pack>true</Pack>
        <PackagePath>tools/$(TargetFramework)/any/</PackagePath>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="$(TodWindowsOutputPath)\System.DirectoryServices.Protocols.dll">
        <Pack>true</Pack>
        <PackagePath>tools/$(TargetFramework)/any/</PackagePath>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
      <Content Include="$(TodWindowsOutputPath)\System.Windows.Forms.DataVisualization.dll">
        <Pack>true</Pack>
        <PackagePath>tools/$(TargetFramework)/any/</PackagePath>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

  </Target>

  <Target Name="CleanArtifacts" AfterTargets="Clean">
    <RemoveDir Directories="$(ArtifactsPath)" />
  </Target>

</Project>
